name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  API_URL: https://elkw2806.church.tools/api
  ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: setup
        run: |
          make setup

      - name: run tests
        run: |
          make test
