name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pytest cache
        id: pytest-cache
        uses: actions/cache@v2
        with:
          path: .pytest_cache
          key: ${{ runner.os }}-pytest-cache

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: setup
        run: |
          make setup

      - name: show pytest cache
        run: |
          .venv/bin/pipenv run pytest --cache-show

      - name: run tests
        run: |
          make test
