name: Test-Workflow for CT API
on:
  workflow_dispatch:

env:
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: run check
        run: |
          curl -X GET -H 'Authorization: Login ${{ secrets.ADMIN_TOKEN }}' ${{ env.API_BASE_URL }}/whoami
        
        
